version: '2'
services:
  msgateway-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/msgateway/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=msgateway
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
